/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import bingo.Controlador;

/**
 *
 * @author Personal
 */
public class mainUI extends javax.swing.JFrame {

    /**
     * Creates new form mainUI
     */
    public mainUI() { //TODO: hay que arreglar esto que esta inicializando el juego antes de mostrar en la pantalla
        initComponents();
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carton = new javax.swing.JPanel();
        b = new javax.swing.JLabel();
        i = new javax.swing.JLabel();
        n = new javax.swing.JLabel();
        g = new javax.swing.JLabel();
        o = new javax.swing.JLabel();
        b1 = new javax.swing.JPanel();
        xB1 = new javax.swing.JLabel();
        numB1 = new javax.swing.JLabel();
        b2 = new javax.swing.JPanel();
        xB2 = new javax.swing.JLabel();
        numB2 = new javax.swing.JLabel();
        b3 = new javax.swing.JPanel();
        xB3 = new javax.swing.JLabel();
        numB3 = new javax.swing.JLabel();
        b4 = new javax.swing.JPanel();
        xB4 = new javax.swing.JLabel();
        numB4 = new javax.swing.JLabel();
        b5 = new javax.swing.JPanel();
        xB5 = new javax.swing.JLabel();
        numB5 = new javax.swing.JLabel();
        i1 = new javax.swing.JPanel();
        xI1 = new javax.swing.JLabel();
        numI1 = new javax.swing.JLabel();
        i2 = new javax.swing.JPanel();
        xI2 = new javax.swing.JLabel();
        numI2 = new javax.swing.JLabel();
        i3 = new javax.swing.JPanel();
        xI3 = new javax.swing.JLabel();
        numI3 = new javax.swing.JLabel();
        i4 = new javax.swing.JPanel();
        xI4 = new javax.swing.JLabel();
        numI4 = new javax.swing.JLabel();
        i5 = new javax.swing.JPanel();
        xI5 = new javax.swing.JLabel();
        numI5 = new javax.swing.JLabel();
        n1 = new javax.swing.JPanel();
        xN1 = new javax.swing.JLabel();
        numN1 = new javax.swing.JLabel();
        n2 = new javax.swing.JPanel();
        xN2 = new javax.swing.JLabel();
        numN2 = new javax.swing.JLabel();
        n3 = new javax.swing.JPanel();
        X = new javax.swing.JLabel();
        n4 = new javax.swing.JPanel();
        xN4 = new javax.swing.JLabel();
        numN4 = new javax.swing.JLabel();
        n5 = new javax.swing.JPanel();
        xN5 = new javax.swing.JLabel();
        numN5 = new javax.swing.JLabel();
        g1 = new javax.swing.JPanel();
        xG1 = new javax.swing.JLabel();
        numG1 = new javax.swing.JLabel();
        g2 = new javax.swing.JPanel();
        xG2 = new javax.swing.JLabel();
        numG2 = new javax.swing.JLabel();
        g3 = new javax.swing.JPanel();
        xG3 = new javax.swing.JLabel();
        numG3 = new javax.swing.JLabel();
        g4 = new javax.swing.JPanel();
        xG4 = new javax.swing.JLabel();
        numG4 = new javax.swing.JLabel();
        g5 = new javax.swing.JPanel();
        xG5 = new javax.swing.JLabel();
        numG5 = new javax.swing.JLabel();
        o1 = new javax.swing.JPanel();
        xO1 = new javax.swing.JLabel();
        numO1 = new javax.swing.JLabel();
        o2 = new javax.swing.JPanel();
        xO2 = new javax.swing.JLabel();
        numO2 = new javax.swing.JLabel();
        o3 = new javax.swing.JPanel();
        xO3 = new javax.swing.JLabel();
        numO3 = new javax.swing.JLabel();
        o4 = new javax.swing.JPanel();
        xO4 = new javax.swing.JLabel();
        numO4 = new javax.swing.JLabel();
        o5 = new javax.swing.JPanel();
        xO5 = new javax.swing.JLabel();
        numO5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Bola = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Play = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));

        carton.setBackground(new java.awt.Color(255, 255, 255));
        carton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_b_30px.png"))); // NOI18N

        i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_i_30px.png"))); // NOI18N

        n.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_n_30px.png"))); // NOI18N

        g.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_g_30px.png"))); // NOI18N

        o.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_o_30px.png"))); // NOI18N

        b1.setBackground(new java.awt.Color(204, 255, 255));
        b1.setPreferredSize(new java.awt.Dimension(30, 30));
        b1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        b1.add(xB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numB1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numB1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numB1.setText("00");
        b1.add(numB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        b2.setBackground(new java.awt.Color(204, 255, 255));
        b2.setPreferredSize(new java.awt.Dimension(30, 30));
        b2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        b2.add(xB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numB2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numB2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numB2.setText("00");
        b2.add(numB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        b3.setBackground(new java.awt.Color(204, 255, 255));
        b3.setPreferredSize(new java.awt.Dimension(30, 30));
        b3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        b3.add(xB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numB3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numB3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numB3.setText("00");
        b3.add(numB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        b4.setBackground(new java.awt.Color(204, 255, 255));
        b4.setPreferredSize(new java.awt.Dimension(30, 30));
        b4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        b4.add(xB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numB4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numB4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numB4.setText("00");
        b4.add(numB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        b5.setBackground(new java.awt.Color(204, 255, 255));
        b5.setPreferredSize(new java.awt.Dimension(30, 30));
        b5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xB5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        b5.add(xB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numB5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numB5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numB5.setText("00");
        b5.add(numB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        i1.setBackground(new java.awt.Color(204, 255, 255));
        i1.setPreferredSize(new java.awt.Dimension(30, 30));
        i1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        i1.add(xI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numI1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numI1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numI1.setText("00");
        i1.add(numI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        i2.setBackground(new java.awt.Color(204, 255, 255));
        i2.setPreferredSize(new java.awt.Dimension(30, 30));
        i2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        i2.add(xI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numI2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numI2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numI2.setText("00");
        i2.add(numI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        i3.setBackground(new java.awt.Color(204, 255, 255));
        i3.setPreferredSize(new java.awt.Dimension(30, 30));
        i3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        i3.add(xI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numI3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numI3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numI3.setText("00");
        i3.add(numI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        i4.setBackground(new java.awt.Color(204, 255, 255));
        i4.setPreferredSize(new java.awt.Dimension(30, 30));
        i4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xI4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        i4.add(xI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numI4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numI4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numI4.setText("00");
        i4.add(numI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        i5.setBackground(new java.awt.Color(204, 255, 255));
        i5.setPreferredSize(new java.awt.Dimension(30, 30));
        i5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xI5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        i5.add(xI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numI5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numI5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numI5.setText("00");
        i5.add(numI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        n1.setBackground(new java.awt.Color(204, 255, 255));
        n1.setPreferredSize(new java.awt.Dimension(30, 30));
        n1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        n1.add(xN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numN1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numN1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numN1.setText("00");
        n1.add(numN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        n2.setBackground(new java.awt.Color(204, 255, 255));
        n2.setPreferredSize(new java.awt.Dimension(30, 30));
        n2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        n2.add(xN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numN2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numN2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numN2.setText("00");
        n2.add(numN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        n3.setBackground(new java.awt.Color(204, 255, 255));
        n3.setPreferredSize(new java.awt.Dimension(30, 30));

        X.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N

        javax.swing.GroupLayout n3Layout = new javax.swing.GroupLayout(n3);
        n3.setLayout(n3Layout);
        n3Layout.setHorizontalGroup(
            n3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, n3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(X))
        );
        n3Layout.setVerticalGroup(
            n3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, n3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(X))
        );

        n4.setBackground(new java.awt.Color(204, 255, 255));
        n4.setPreferredSize(new java.awt.Dimension(30, 30));
        n4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xN4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        n4.add(xN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numN4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numN4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numN4.setText("00");
        n4.add(numN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        n5.setBackground(new java.awt.Color(204, 255, 255));
        n5.setPreferredSize(new java.awt.Dimension(30, 30));
        n5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xN5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        n5.add(xN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numN5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numN5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numN5.setText("00");
        n5.add(numN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        g1.setBackground(new java.awt.Color(204, 255, 255));
        g1.setPreferredSize(new java.awt.Dimension(30, 30));
        g1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        g1.add(xG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numG1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numG1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numG1.setText("00");
        g1.add(numG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        g2.setBackground(new java.awt.Color(204, 255, 255));
        g2.setPreferredSize(new java.awt.Dimension(30, 30));
        g2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        g2.add(xG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numG2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numG2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numG2.setText("00");
        g2.add(numG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        g3.setBackground(new java.awt.Color(204, 255, 255));
        g3.setPreferredSize(new java.awt.Dimension(30, 30));
        g3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xG3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        g3.add(xG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numG3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numG3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numG3.setText("00");
        g3.add(numG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        g4.setBackground(new java.awt.Color(204, 255, 255));
        g4.setPreferredSize(new java.awt.Dimension(30, 30));
        g4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xG4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        g4.add(xG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numG4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numG4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numG4.setText("00");
        g4.add(numG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        g5.setBackground(new java.awt.Color(204, 255, 255));
        g5.setPreferredSize(new java.awt.Dimension(30, 30));
        g5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xG5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        g5.add(xG5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numG5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numG5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numG5.setText("00");
        g5.add(numG5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        o1.setBackground(new java.awt.Color(204, 255, 255));
        o1.setPreferredSize(new java.awt.Dimension(30, 30));
        o1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        o1.add(xO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numO1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numO1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numO1.setText("00");
        o1.add(numO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        o2.setBackground(new java.awt.Color(204, 255, 255));
        o2.setPreferredSize(new java.awt.Dimension(30, 30));
        o2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xO2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        o2.add(xO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numO2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numO2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numO2.setText("00");
        o2.add(numO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        o3.setBackground(new java.awt.Color(204, 255, 255));
        o3.setPreferredSize(new java.awt.Dimension(30, 30));
        o3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xO3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        o3.add(xO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numO3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numO3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numO3.setText("00");
        o3.add(numO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        o4.setBackground(new java.awt.Color(204, 255, 255));
        o4.setPreferredSize(new java.awt.Dimension(30, 30));
        o4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xO4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        o4.add(xO4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numO4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numO4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numO4.setText("00");
        o4.add(numO4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        o5.setBackground(new java.awt.Color(204, 255, 255));
        o5.setPreferredSize(new java.awt.Dimension(30, 30));
        o5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xO5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_30px.png"))); // NOI18N
        o5.add(xO5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        numO5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numO5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numO5.setText("00");
        o5.add(numO5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        javax.swing.GroupLayout cartonLayout = new javax.swing.GroupLayout(carton);
        carton.setLayout(cartonLayout);
        cartonLayout.setHorizontalGroup(
            cartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(cartonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cartonLayout.createSequentialGroup()
                        .addComponent(b)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(i)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(n)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(g)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(o))
                    .addGroup(cartonLayout.createSequentialGroup()
                        .addGroup(cartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(i1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(i2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(i3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(i5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(i4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(o1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(o2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(o3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(o4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(o5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cartonLayout.setVerticalGroup(
            cartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(o)
                    .addComponent(g)
                    .addComponent(n)
                    .addComponent(i)
                    .addComponent(b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cartonLayout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cartonLayout.createSequentialGroup()
                        .addComponent(i1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cartonLayout.createSequentialGroup()
                        .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cartonLayout.createSequentialGroup()
                        .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cartonLayout.createSequentialGroup()
                        .addComponent(o1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(o2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(o3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(o4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(o5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setMinimumSize(new java.awt.Dimension(110, 110));
        jPanel1.setPreferredSize(new java.awt.Dimension(110, 110));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bola.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Bola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bola.setText("00");
        jPanel1.add(Bola, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_circled_100px.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_play_40px.png"))); // NOI18N
        Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(carton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Play)
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(Play)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseClicked
        Controlador control = new Controlador(Bola,numB1,numB2,numB3,numB4,numB5,numI1,numI2,numI3,numI4,numI5,numN1,numN2,numN4,numN5,numG1,numG2,numG3,numG4,numG5,numO1,numO2,numO3,numO4,numO5,xB1,xB2,xB3,xB4,xB5,xI1,xI2,xI3,xI4,xI5,xN1,xN2,xN4,xN5,xG1,xG2,xG3,xG4,xG5,xO1,xO2,xO3,xO4,xO5);  
        control.Controlar();
    }//GEN-LAST:event_PlayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainUI().setVisible(true);        
            }
        });
        
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bola;
    private javax.swing.JLabel Play;
    private javax.swing.JLabel X;
    private javax.swing.JLabel b;
    private javax.swing.JPanel b1;
    private javax.swing.JPanel b2;
    private javax.swing.JPanel b3;
    private javax.swing.JPanel b4;
    private javax.swing.JPanel b5;
    private javax.swing.JPanel carton;
    private javax.swing.JLabel g;
    private javax.swing.JPanel g1;
    private javax.swing.JPanel g2;
    private javax.swing.JPanel g3;
    private javax.swing.JPanel g4;
    private javax.swing.JPanel g5;
    private javax.swing.JLabel i;
    private javax.swing.JPanel i1;
    private javax.swing.JPanel i2;
    private javax.swing.JPanel i3;
    private javax.swing.JPanel i4;
    private javax.swing.JPanel i5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel n;
    private javax.swing.JPanel n1;
    private javax.swing.JPanel n2;
    private javax.swing.JPanel n3;
    private javax.swing.JPanel n4;
    private javax.swing.JPanel n5;
    private javax.swing.JLabel numB1;
    private javax.swing.JLabel numB2;
    private javax.swing.JLabel numB3;
    private javax.swing.JLabel numB4;
    private javax.swing.JLabel numB5;
    private javax.swing.JLabel numG1;
    private javax.swing.JLabel numG2;
    private javax.swing.JLabel numG3;
    private javax.swing.JLabel numG4;
    private javax.swing.JLabel numG5;
    private javax.swing.JLabel numI1;
    private javax.swing.JLabel numI2;
    private javax.swing.JLabel numI3;
    private javax.swing.JLabel numI4;
    private javax.swing.JLabel numI5;
    private javax.swing.JLabel numN1;
    private javax.swing.JLabel numN2;
    private javax.swing.JLabel numN4;
    private javax.swing.JLabel numN5;
    private javax.swing.JLabel numO1;
    private javax.swing.JLabel numO2;
    private javax.swing.JLabel numO3;
    private javax.swing.JLabel numO4;
    private javax.swing.JLabel numO5;
    private javax.swing.JLabel o;
    private javax.swing.JPanel o1;
    private javax.swing.JPanel o2;
    private javax.swing.JPanel o3;
    private javax.swing.JPanel o4;
    private javax.swing.JPanel o5;
    private javax.swing.JLabel xB1;
    private javax.swing.JLabel xB2;
    private javax.swing.JLabel xB3;
    private javax.swing.JLabel xB4;
    private javax.swing.JLabel xB5;
    private javax.swing.JLabel xG1;
    private javax.swing.JLabel xG2;
    private javax.swing.JLabel xG3;
    private javax.swing.JLabel xG4;
    private javax.swing.JLabel xG5;
    private javax.swing.JLabel xI1;
    private javax.swing.JLabel xI2;
    private javax.swing.JLabel xI3;
    private javax.swing.JLabel xI4;
    private javax.swing.JLabel xI5;
    private javax.swing.JLabel xN1;
    private javax.swing.JLabel xN2;
    private javax.swing.JLabel xN4;
    private javax.swing.JLabel xN5;
    private javax.swing.JLabel xO1;
    private javax.swing.JLabel xO2;
    private javax.swing.JLabel xO3;
    private javax.swing.JLabel xO4;
    private javax.swing.JLabel xO5;
    // End of variables declaration//GEN-END:variables
}
